# Generated by Django 5.2.1 on 2025-05-23 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='JogadorAvulso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicao', models.CharField(max_length=50)),
                ('disponibilidade', models.BooleanField(default=True)),
                ('nota', models.FloatField(default=0.0)),
                ('data_insert', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(db_column='id_pessoa', on_delete=django.db.models.deletion.CASCADE, to='pia_app.pessoa')),
            ],
            options={
                'db_table': 'jogador_avulso',
            },
        ),
    ]
