# Generated by Django 5.2.1 on 2025-05-23 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadoravulso',
            name='disponibilidades',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jogadoravulso',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jogadoravulso',
            name='pessoa',
            field=models.ForeignKey(db_column='id_pessoa', on_delete=django.db.models.deletion.CASCADE, related_name='avulsos', to='pia_app.pessoa'),
        ),
    ]
